name: eyesopen
description: "It would never be wasted."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1 
  flutter_switch: ^0.3.2
  flutter_animate: ^4.0.3  # New dependency for animations
  provider: 6.1.2 
  shared_preferences: ^2.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login.jpg
    - assets/background1.png
